general:
  printStackTraces: false
  showquery: false
database:
  username: username
  password: password
  host: localhost
  port: 3306
  database: schema
  extrasettings: autoReconnect=true&useSSL=false