name: SweetieLib
main: net.shonx.lib.SweetieLib
version: @VERSION@
api-version: 1.19
authors: [SweetieBelle]
softdepend: [LuckPerms]
description: >
             A library plugin for some of my other plugins